import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Col, Container, Row } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container>
          <Row>
            <div id="topbar">
              <div id="socials">
                socials
              </div>
              <div id="user_menu">dropdown menu</div>
            </div>
            <div id="header">header</div>
            <div id="main_menu" className="bg-info">main menu</div>
          </Row>
        </Container>
        <Container>
          <Row>
            <Col sm={8} md={9} className="bg-light">
              <main>
                {children}
              </main>
            </Col>
            <Col className="bg-secondary">
              sidebar
            </Col>
          </Row>
          <Row>
            <div id="footer" className="bg-warning">
              footer
            </div>
          </Row>
        </Container>
      </body>
    </html>
  );
}
